### ISSUE TITLE
changelog in reverse order?

### ISSUE THREAD

**Issue by GitHubWebb** [metcalfc/changelog-generator#41]
I want  ${{ steps.changelog.outputs.changelog }} is reverse order
Changelog
7381c2c - add body
6c58ae2 - add console 2020年12月08日10:28:02
9253cb6 - add console 2020年12月08日10:37:08
6dd71dc - add console 2020年12月08日10:42:03
eeb7ae0 - Update release-drafter.yml
f411180 - Update release-drafter.yml
ad14d75 - no message

**Comment by metcalfc** [comment]
Once you have the output you can hack it any way you'd like in follow on steps. The action will stick to oldest first, just because its the format the projects that are already using this expect.

But its pretty easy to flip it:

```
- name: Get the changelog
        run: echo "${{ steps.release.outputs.changelog }}" | tac
```

In this case I'm using `tac` which is `cat` backwards. Does the same thing as `cat` except in reverse.

``` 
$ echo "foo\nbar"| tac
bar
foo
```
