### ISSUE TITLE
Add an ability to add the changes in the submodules to the changelog

### ISSUE THREAD

**Issue by AChep** [metcalfc/changelog-generator#43]

**Comment by metcalfc** [comment]
This would be a pretty large undertaking. You'd have to compare the submodule files at the base and at the head and then for each entry get the list of changes and render those out.  This isn't something I can sign up to build or maintain. If someone else wants to build it, write tests for it, and help maintain it I'd be willing to review it. It would need to be optional, I think most folks that use this action are here because it is so simple.

I'm going to close this out for now. But I'll label it help-wanted so that if anyone wants to come around and do the work they can find it.
