### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by thibaultserti** [metcalfc/changelog-generator#51]
The action was doing very well last week and today it crashes due to insufficient privilege ...

Do you have an idea from where it could come ?

```console
Run metcalfc/changelog-generator@v0.4.4
  with:
    myToken: ***
    head-ref: ed1baa724edbfca616424d27fb92ddf6cfc6bb28
    base-ref: v3.0-1
head-ref: ed1baa724edbfca616424d27fb92ddf6cfc6bb28
base-ref: v3.0-1
/home/runner/work/_actions/metcalfc/changelog-generator/v0.4.4/dist/changelog.sh ed1baa724edbfca616424d27fb92ddf6cfc6bb28 v3.0-1 ovh/debian-cis
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
Error: Could not generate changelog between references because: The process '/home/runner/work/_actions/metcalfc/changelog-generator/v0.4.4/dist/changelog.sh' failed with exit code 128
```

Here is the workflow :
https://github.com/ovh/debian-cis/runs/1761796044?check_suite_focus=true

**Comment by metcalfc** [comment]
That is an odd error. So whats happening in the script is that by default an action checkout is shallow (it only checks out the files for the SHA in question, not the full repository history). We unshallow the checkout so we can get the full history between any two commits. 

So in this case when we go to unshallow the history, its failing because the user doesn't have write permissions on the git directory.

But ... the user just checked out the repository in the step two above in your case. If you re run this do you get the same error? Or is this an intermittent failure?

**Comment by thibaultserti** [comment]
Yes if I rerun I get the same error.

**Comment by thibaultserti** [comment]
And today it just works ... No idea what has happened here :/

**Comment by metcalfc** [comment]
Thank you for the update. Actions work directory seem to be a little flakey. If this happens again let me know and I'll ping the actions folks.
