### ISSUE TITLE
Override git log command

### ISSUE THREAD

**Issue by coltdorsey** [metcalfc/changelog-generator#98]
Is there a way to modify the changelog via github actions to use this git log command:

```
log=$(git log "${base_ref}...${head_ref}" \
  --pretty=format:"* [\`%h\`](http://github.com/${{ github.event.repository.full_name }}/commit/%H) %b - %s" \ 
  --grep="Merge pull request #" \
  --reverse)
```

I'm having a lot of syntax issues when trying to accomplish this via your https://github.com/metcalfc/changelog-generator#simple-output-modifications section

**Comment by coltdorsey** [comment]
Some progress:

```
          set -o noglob
          log=$(git log "v0.3.7...v0.3.8" \
          --pretty=format:"* [\`%h\`](http://github.com/${{ github.event.repository.full_name }}/commit/%H) %b - %s" --grep="Merge pull request #" \
          --reverse)
          echo "::set-output name=modified::$log"
```

**Comment by coltdorsey** [comment]
I guess the last bit is getting the correct references to base-ref and head-ref within the github action. Any help appreciated.

**Comment by metcalfc** [comment]
There isn’t currently but there are a couple folks now who I’ve seen it could be useful for. 

The changelog script is in bash so the action would have to pass the command or the args as an arg/env var. So it would certainly be fragile. 

Is all you want to do is drop the reverse? Or do you want to alter the format string?

**Comment by metcalfc** [comment]
@coltdorsey I updated the way the log is generated in v3.0.0. I changed the default to match `git log` ie chronological. You now need to set `reverse: 'true'` in the workflow for reverse. But I just realized I was looking at the wrong ticket. So thats my mistake. I see you're using reverse so when you update, if you are using your script you'll be fine. Otherwise set the input in the workflow.
